# Generated by Django 4.0.4 on 2022-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorycode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_code', models.CharField(max_length=100)),
                ('billing_code', models.CharField(max_length=20)),
                ('default_rates', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
